### ISSUE TITLE
Improve code health

### ISSUE THREAD

**Issue by dfurrer** [RE-Lab-Projects/hplib#20]
First of all let me say that this is a super important problem space and the library looks very useful. Thanks for writing it. I'm happy to have come across it and see it being actively developed. (And I have some cool ideas on what it could be used for..)

Anyway, I was trying to run the simulation snippet from **4.B Simulate a time series** and ran into the following error:

```
File ~/Code/hplib/hplib/hplib.py:607, in HeatPump.simulate(self, t_in_primary, t_in_secondary, t_amb, mode, p_th_min)
    605             cop = p_th/p_el                           
--> 606 if cop <= 1:
    607     cop = 1
    608     p_el = self.p_th_ref

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
I believe the code there should not be run if `cop` is an `np.ndarray` as that is already handled above.

I then looked a bit more at the code and would like to offer a few observations and make some suggestions for improving it:

It appears that the module `hplib` has both (1) a top-level `simulate()` method as well as (2) `HeatPump.simulate()` which appear to be quite similar but have some (I believe) undesired differences.

 * None of the implementation code is shared. Are both methods really needed? If so can one just call the other?
 * It would be good to have a unit test. E.g. that runs the examples from the Notebook.
 * The docstring of (2) wrongly mentions `parameters`. That isn't actually a supported argument.
 * Pytypes for `t_in_primary` and `t_in_secondary` are `any` for (1) but `float` for (2). I believe the correct type should be `Union[float, numpy.ndarray]`.
 * Minor: `mode` being an `int` makes the methods harder to use and the code harder to read. I believe an `enum` should be used here.

**Comment by xihaui** [comment]
Thanks for having a look and your list of improvements. 
I tried to fix the error you had and improved the Code a little. 
I also had a look  on `simulate()` and `HeatPump.simulate()` and they are supposed to be similar. It would be nice to combine them. 

Only differences:
- The input of `simulate()` are parameters and the output is a DataFrame
- The input of `HeatPump.simulate()` are self and  the output is a Dict.

The docstrings and the tests would be a good improvement.

**Comment by dfurrer** [comment]
Thanks, I pulled the latest version and can confirm that the bug which broke **4.B Simulate a time series** appears to be resolved.
